server:
  port: 8089
spring:
  application:
    name: customer-service

eureka:
  client:
    register-with-eureka: false #注册到Eureka的注册中心
    fetch-registry: false #获取注册实例列表
    service-url:
      defaultZone: http://RaviR-Dev:8671/eureka/ #配置注册中心地址
management:
  endpoints:
    web:
      exposure:
        include: '*'