server:
  port: 9091
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: https://example.org
          predicates:
          - name: Cookie
            args:
              name: mycookie
              regexp: mycookievalue	

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka/